### ISSUE TITLE
Catchall-Account

### ISSUE THREAD

**Issue by kaffeeringe** [Automattic/wordpress-activitypub#1]
Hej,
I write my comment here because I am not sure if your OStatus-suite has a future with ActivityPub at the horizon.

It would be cool if it was possible to follow the whole blog and not just accounts. At the moment you can just follow @user1@example.com, @user2@example.com, @user3@example.com - it would be nice if I could just follow *@example.com. I don't care what * is or if I am able to customize it...

**Comment by pfefferle** [comment]
hmm... do you ask because you are the only one using the blog and you want to use the main domain instead of the `/author/...` domain? Or do you really have a blog with different authors and you want to follow the whole blog?

**Comment by pfefferle** [comment]
In the end it will be fixed in both plugins, because ActivityPub does not really define the `@user@domain.tld` stuff, but still uses the OStatus/WebFinger stuff instead.

**Comment by kaffeeringe** [comment]
I run several Wordpress-sites. My blog kaffeeringe.de has only me as author. But I am thinking about organisations that use Wordpress. There are most likely more than one author. Or the author changes over time. For exampel https://soz.is/ offers Wordpress to SPD volunteer organizations. They sometimes change the webmaster and don't just pass on the account data. 

In my case I realized that my admin-username is also my ActivityPub-username. I changed that. I changed my username to @steffen@kaffeeringe.de, turned it into a non-admin account and Created a new admin-account with a different name. It would also be easier for one-person blogs not to publicly appear with their admin-usernames.

**Comment by DeadSuperHero** [comment]
One way to think about it, perhaps, is that the blog could have a master Actor assigned to it, that basically reshares all of the posts made by that blog's members?

That's effectively how PeerTube associates accounts and channels. An account Actor has multiple channels, each channel is itself a separate Actor that consists of reshared posts from the master account.

![peertube-actor-channels](https://user-images.githubusercontent.com/401560/46043614-56175b00-c0cd-11e8-919a-601f96aab9c2.jpeg)

The only difference, perhaps, is that the attribution would point in the other direction, where the blog Actor is resharing the statuses coming from individual users.

**Comment by pfefferle** [comment]
any suggestions for the identifier? (`identifier@domain.tld`)

**Comment by kaffeeringe** [comment]
blog@example.com

Or you make that customizable...

**Comment by Suitbert** [comment]
@blog@example.com would help me with my multi-user problem at wordpress too. Then I would not have to care about those author pages ...

**Comment by transfluxus** [comment]
i would like that feature too. can we maybe try, i send anything in activityPub and the wp settings screen shows it, ... makes it easier setable, from which individual or groups of accounts, where new activities are created and sent to setable outboxes.

**Comment by transfluxus** [comment]
ok, lets leave out the "sending anything in activityPub" for now. the basic options I think as a admin on a wp blog with a couple of other users would be

- a list of wp-users > activitypub actor: assign groups of wp users to certain activitypub actors

this list would allow both, Catchall or one activityPub actor per wp user or anything mixed. I guess as first part of the setting, one could some UI to create/manage activityPub actor running through the wp blog.

**Comment by manoelnascimento** [comment]
#43 has been recently opened with a similar question. After reading carefully this topic (and not being a programming expert), I was able to conceptualize two possible ways to make it work:

a) Insert an option in the "ActivityPub Settings" page that allows admins to choose between "Follow the whole blog", "Follow blog sections" or "Follow author". In this case, for each option ActivityPub would create one user/actor for the whole blog (e.g., "wholeblog@blog.net"), one user/actor for each blog section (e.g., "technology@blog.net", "travel@blog.net", "fun@blog.net" and so on) and one user/actor for each blog author (as it does today). Admins would then choose what suits them best.

b) Create an option in the "ActivityPub Settings" that allows the automated republishing of the whole site or any of its sections in a preexisting profile (e.g., "wholeblog@mastodon.social", "travel@mastodon.social", "fun@mastodon.social" etc.).

This is an important issue because, for example, there are news sites (eg, WSJ, The Economist) that use RSS to spread their news by section, by author, or by grouping all site publications in a single stream. If something similar is made possible using the ActivityPub protocol using WordPress, this would be a further stimulus for growth in protocol usage.

**Comment by schiessle** [comment]
For the whole blog you could either use `<blog title>@<blog url>` or let the admin define a random actor name. I agree with @manoelnascimento that having "meta users" for categories/sections and tags might be useful as well.

**Comment by tobiasd** [comment]
I like the idea by @schiessle having such a mata user would be really great.

**Comment by JimKillock** [comment]
I echo this. Take an organisation like [Open Rights Group](https://www.openrightsgroup.org/blog/), with a vblog

**Comment by emilydolson** [comment]
I would also love to have this feature. In particular it would be great to turn off the automatic creation of profiles for all users of my site and just have one catch-all account, as my site has a lot of users who do not publish posts and I don't feel comfortable auto-generating profiles for them without their knowledge.

**Comment by heiglandreas** [comment]
For our blog https://24daysindecember.net - which shares posts by multiple authors over the course of the 24 days leading up to 25th of december - we would also really apprechiate some way that people can just subscribe to the whole blog to follow those separate articles. Having to subscribe to the separate authors does not make sense as they are not known beforehand. 

So having one catchall, that people can subscribe to while still maintaining the ownership of the post towards a distinct user would really be helpful!

**Comment by mediaformat** [comment]
> having one catchall, that people can subscribe to while still maintaining the ownership of the post towards a distinct user would really be helpful!

A straight-forward solution to this would be to have the catch-all account `Announce`/ Share all the Posts with its followers.

**Comment by mediaformat** [comment]
One thing to think about is how replies would work.

@example  Would all replies

**Comment by mediaformat** [comment]
There are 2 different use-cases here: 
1. Multiple actor model, where authors posts are shared by a main Site actor
2. Single actor Site model

In this single Actor model, who would be able reply to comments? 
Would it make sense for any [author](https://wordpress.org/support/article/roles-and-capabilities/#author) to have the authority to reply, or should it map to an [editor](https://wordpress.org/support/article/roles-and-capabilities/#editor) role?

**Comment by emilydolson** [comment]
I think in an ideal world, it would be possible to configure which role it maps to (I've got a variety of custom roles on my site). But failing that, in my case it would make the most sense for it to map to an editor role. Not sure what set-ups others use.

**Comment by mediaformat** [comment]
perhaps it would make most sense to map it to the [moderate_comments](https://wordpress.org/support/article/roles-and-capabilities/#moderate_comments) capability

**Comment by danimrich** [comment]
I too would prefer to be able to have one Mastodon profile for the whole blog.

For me, the reason is a bit different: I tend to use my real name and the same profile pic. Thus, the blog's Mastodon profile actually looks as if it impersonates my primary Mastodon account. I don't want people to confuse one with the other.

**Comment by kerim** [comment]
This is how I would like to use it as well. I just want people to be able to follow our multiuser blog with something like blog@sitename.org. We often have new guest bloggers and with the current system people would have to add a new person to follow every time they posted!

**Comment by Mannshoch** [comment]
I would propose to have a switch in activity settings to change from user to whole blog and - what I need - category.
Also, I need a Follow button for the Website that I could add.
Se also: https://github.com/pfefferle/wordpress-activitypub/issues/14 ( https://github.com/pfefferle/wordpress-activitypub/issues/145 )

**Comment by majorlinux** [comment]
> I too would prefer to be able to have one Mastodon profile for the whole blog.
> 
> For me, the reason is a bit different: I tend to use my real name and the same profile pic. Thus, the blog's Mastodon profile actually looks as if it impersonates my primary Mastodon account. I don't want people to confuse one with the other.

Exactly this! Had it configured then all of a sudden noticed that I'd be following myself or having people follow two different versions of me.

**Comment by JimKillock** [comment]
Hey @pfefferle could you give us an idea whether this can be prioritised? I'm not sure if there is a reason why this hasn't happened (eg reworking the code is difficult, or you don't have time to do, or need funding, or other); or perhaps it is in fact at the top of your pile, but it would be great to know your thoughts on it and if it is something that can be done soon.

I am certain it is blocking a lot of take up. This plug in something I could push with lots of organisations as a no brainer thing to do to get them on the Fediverse, but without this feature it won't work for most organisations with multiple authors who change over time (which is nearly all organisations tbh).

**Comment by pfefferle** [comment]
Hey @JimKillock 

Valid question! At the moment it is simply a time problem! I am currently thinking about my options to invest more time in this and my other plugins. I hope I have an update for you all soon!

**Comment by alexture** [comment]
@pfefferle good luck and don't overwork yourself either! You're doing amazing work :)

**Comment by JimKillock** [comment]
Thank you @pfefferle :)

**Comment by JimKillock** [comment]
> If this happens (which would be amazing!!) it would be great to then give a GUI for adding aliases to accounts that exist on WordPress so that people can use the domain name but connect it to a mastodon/other fediverse account held elsewhere.
> 
> An example of what I mean is here: https://blog.maartenballiauw.be/post/2022/11/05/mastodon-own-donain-without-hosting-server.html

Should we add a separate issue? I agree this is a great idea but is probably a different problem to solve.

**Comment by Mannshoch** [comment]
Please allow me to propose a Mockup. I'm not that familiar with how WordPress work in background. But I hope I'm able to transfer the Idea I have.
![image](https://user-images.githubusercontent.com/7795891/204844207-fff02121-9d5e-47a7-802d-15aa984e350d.png)

**Comment by pfefferle** [comment]
@Mannshoch I like your ideas, but the categories part makes things really complicated :)

I like it!

**Comment by adegans** [comment]
I see a lot of ideas flopping around and everyone has a little different idea for it - From a generic feed for everything to category based stuff...
All good and probably valid.

But if there is a time constraint or a complexity to it that is hard to figure out for now that's causing delays pick a simple implementation first.

To my mind that would be simply an option to set a feed name that streams everything (exactly like a RSS feed does now) and that's it.
For that approach you could even use the RSS feed as a basis and convert it to a activitypub feed perhaps? (not exactly, but you know, its a similar feed in a different format basically...)

See how that works, hear what people think of it.
Then once you have that all figured out, either add a filter or sub-function for category based feeds if that still makes sense.

If there is a question for duplicate content in different feeds then have the plugin assign a hash or ID in the post meta as soon as the plugin sticks it in a feed (the everything feed, user, category, custom or otherwise) and let ALL feeds rely on that. Simple and effective.

**Comment by sjlongland** [comment]
Just a thought for the common feed, some have rightfully pointed out that someone who follows both the _main_ account, and individual authors, may find themselves with duplicates in the timeline.

I wonder if instead of posting it _as_ the main account, the main account simply "boosts" whatever is posted by the authors?  That way, the followers can see whom has been posting what, but still follow a "single" point if they so choose.

**Comment by juengling** [comment]
After reading all of those posts, I think it would be the best way to implement them all to follow ...

- individual authors
- categories
- hashtags
- whole blog

... perhaps with a checkbox in the backend GUI for each option to individually choose what is to be exported.

(I have absolutely no idea how complicated this may be, because I never did programming in PHP.)
