### ISSUE TITLE
Feature Request: Make plugin to turn blog also into a bluesky node

### ISSUE THREAD

**Issue by eiland-asbl** [Automattic/wordpress-activitypub#1029]
### What

Call me a noob, but I just tried to make an account at blueky, and it offered me to sign up using my own server. So then, wouldnt it be possible to make thise plugin to also serve as a [blsky-pds](pds)?

### Why

obviously this would be a kill featrue

### How

no clue

**Comment by pfefferle** [comment]
Thanks for your request @eiland-asbl but I don't think this will happen any time soon! Bluesky has a lot of requirements that are hard to implement in PHP and on shared hosting.

We are looking into the AP-Protocol though and maybe there will be a dedicated plugin or service in the future.

In the meantime you could have a look at https://fed.brid.gy/ to bridge your blog to bluesky.

I will close this for now, because we have still a lot to do for ActivityPub, before looking into something new.
