### ISSUE TITLE
Images in the body get mangled in lemmy

### ISSUE THREAD

**Issue by db0** [Automattic/wordpress-activitypub#1044]
### Quick summary

Example: https://lemmy.dbzer0.com/post/32758507

Image was embedded in the WP post. Got translated as html on lemmy side 

```
<img alt=“” src=“https://i0.wp.com/dbzer0.com/wp-content/uploads/2024/12/image.png?resize=620%2C413&ssl=1” height=“413” width=“620” />
```

### Steps to reproduce

1. post on WP site federated to lemmy.

### What you expected to happen

Images in the body should be converted to something usable by lemmy

### What actually happened

Images are put in as HTML

### Impact

All

### Available workarounds?

No but the platform is still usable

**Comment by pfefferle** [comment]
@db0 this should be reported to lemmy I think!

**Comment by pfefferle** [comment]
Some more context: The plugin does not strip any HTML, because some platforms like friendi.ca support inline images (see image).

![Image](https://github.com/user-attachments/assets/69f3b29a-2b5a-44f9-959d-9972532e85e6)

So I see this in the responsibility of the receiving platform, to remove the HTML that they do not support, instead of encoding it.

**Comment by pfefferle** [comment]
I will close this issue for now, because the plugin seem to work as expected, please feel free to still add comments or re-open if you think it is still a problem.

**Comment by db0** [comment]
One question: Does the plugin know when it's pushing to lemmy vs when it's pushing to friendica?

**Comment by pfefferle** [comment]
we currently do not store this information. but I see what you try to propose :)

my 5 cents: It is way more complicated to have different representations for different platforms. this feels a lot like crossposting, back in the days. I prefer, that every platform should send as much and detailed informations as possible and the receiving should decide what they need and support.

**Comment by db0** [comment]
I do seem to remember that you can declare a post type as text/html or text/markdown like [I do here in fediseer](https://github.com/Fediseer/fediseer/blob/f7370da78ceb1a7ccd6b37481aeaf1860e1b2647/fediseer/messaging.py#L69). Do you do that as well?

**Comment by db0** [comment]
Anyway, the problem here is the usual that happens between two apub implementations. I see it constantly that the developers of each platform interaction which doesn't handle something correctly, insist that the problem is on the other side but ultimately a lot of edge incompatibility like this remains for the end-user.

**Comment by pfefferle** [comment]
> I see it constantly that the developers of each platform interaction which doesn't handle something correctly, insist that the problem is on the other side but ultimately a lot of edge incompatibility like this remains for the end-user.

I totally understand your point and that this might be frustrating and I am totally open to have a discussion about that! I am also willing to do whatever might be needed to have a better user experience, but this is really one of my few stand points, where I really truly believe that this is the right way to go!

**Comment by db0** [comment]
Sure, I see you're now going to be sending the  `text/html` in the metadata, so hopefully with this set, lemmy might be able to convert it accordingly.

**Comment by pfefferle** [comment]
As I said, I am happy to improve the Activity-Object as best as possible... excepts if it is special templates for specific platforms ☺️

/cc @Nutomic

**Comment by Nutomic** [comment]
Lemmy only stores markdown for all post content, so for incoming federated posts it converts any HTML to markdown. It turns out there is a bug in the library used for this conversion, which means [img tags dont get converted if they contain `height` or `width` attributes](https://gitlab.com/Kanedias/html2md/-/issues/15). The library doesnt seem to be actively maintained so a fix could take a while. And alternative libraries for this purpose seem to have issues parsing other things.

What you could do as workaround is remove `width` and `height` attributes from the federated html, or federate your own markdown as [source](https://github.com/LemmyNet/lemmy/blob/main/crates/apub/assets/lemmy/objects/page.json#L13) (probably doesnt make sense as wordpress doesnt seem to use markdown).

**Comment by pfefferle** [comment]
Thanks much for the info @Nutomic !

**Comment by pfefferle** [comment]
So @db0 how are your PHP skills? You could write a filter to remove the attributes from the output before it is federated.

**Comment by db0** [comment]
Pretty much non existent but if you point me in the right direction I could try to hack it
