### ISSUE TITLE
Follow button

### ISSUE THREAD

**Issue by alexture** [Automattic/wordpress-activitypub#145]
Hi! I'd love to put a follow button on my blog, rather than tell people "go follow @name@domain.com". But currently, if I click on the mastodon profile, I'm taken to my author page and as far as I understand, there's no way to sign up from anywhere on that page. Is there a link somewhere that can be used and that I've missed? And if so, would you consider adding an option for an automated follow button on author pages?

**Comment by mediaformat** [comment]
Duplicate of #14

**Comment by pfefferle** [comment]
Keep

**Comment by mwt** [comment]
There's a test of this in action with a completely standalone php script here:

https://chriskthomas.com/fedi-follow/

It's just a proof of concept. I'll update this with the source code once it's released.

**Comment by Cambridgeport90** [comment]
I just followed you… It appears to work from this side of things… haven’t seen a post from you yet, but you’ll be receiving a comment or a like of some sort when I do.

**Comment by mwt** [comment]
I've put up a public general use version that allows your username and instance to be set via query parameters. You can use this service in two ways:

1. (Simplest) You can share the direct url to your follow page on your WordPress site. The syntax is: `https://apfollow.mwt.me/?user=username&instance=instance.tld` for a user with the handle `@username@instance.tld`. Here is [an example of a follow page](https://apfollow.mwt.me/?user=mwt&instance=mathstodon.xyz).
2. (Harder) You can reverse proxy the service to use it on your own domain. For example, the following rule works in my `.htaccess` file on LiteSpeed web server:
```apache
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^users/(.*)/remote_follow$ "https://apfollow.mwt.me/?user=$1&instance=chriskthomas.com" [P,E=Proxy-Host:apfollow.mwt.me,L]
</IfModule>
```
on Apache, it should work with a simpler:
```apache
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^users/(.*)/remote_follow$ "https://apfollow.mwt.me/?user=$1&instance=chriskthomas.com" [P,L]
</IfModule>
```
This will make the follow page accessible for all users at `/users/{username}/remote_follow`, which is the same url scheme used by Mastodon.

**This should work as a general following service for all ActivityPub sites.**

Source code is up on [mwt/apfollow](https://github.com/mwt/apfollow). It's licensed AGPL because I took a bunch of frontend from Mastodon.

**Comment by pfefferle** [comment]
Keep!

**Comment by pfefferle** [comment]
We added a follow block in the newest version!

**Comment by alexture** [comment]
Hmm, it seems that even when I select my account in the widget menu the block still displays the Hello Dolly placeholder account. Am I missing something?
