### ISSUE TITLE
BIO and Avatar

### ISSUE THREAD

**Issue by marc0janssen** [Automattic/wordpress-activitypub#211]
Hi There,

Question: Sinds this a beta software, are the BIO en AVATAR "sync" not just implemented?

I don't see a BIO and the avatar is empty when looking up the account on mastodon.

**Comment by pfefferle** [comment]
The plugin uses the author description as bio and the gravatar as avatar.

**Comment by marc0janssen** [comment]
Waited 6 hours or so... still no avatar and bio from Wordpress activatypub... any hints?

**Comment by marc0janssen** [comment]
Thanks Django. I tested this. But no result yet. Also hashtags are no coming through.

**Comment by marc0janssen** [comment]
The BIO text is updated. SO this seems to work.

Hashtages and avatar are not coming through.

Do you have a hint or so?

**Comment by mediaformat** [comment]
I wonder if it's because of the ports, if you lookup your webfinger you will see `domain:443/`

**Comment by marc0janssen** [comment]
This is the output.

`Request Log

21:09:38 Looking up WebFinger data for acct:marco@theattic.mjanssen.nl
21:09:38 GET https://theattic.mjanssen.nl/.well-known/webfinger?resource=acct%3Amarco%40theattic.mjanssen.nl
JSON Resource Descriptor (JRD)

{
  "subject": "acct:marco@theattic.mjanssen.nl",
  "aliases": [
    "acct:marco@theattic.mjanssen.nl",
    "https://theattic.mjanssen.nl:443/author/marco/",
    "mailto:marco@mjanssen.nl"
  ],
  "links": [
    {
      "rel": "http://webfinger.net/rel/profile-page",
      "type": "text/html",
      "href": "https://theattic.mjanssen.nl:443/author/marco/"
    },
    {
      "rel": "http://webfinger.net/rel/avatar",
      "href": "https://secure.gravatar.com/avatar/df726990448c149512cd5ced0f5718dd?s=96&d=mm&r=g"
    },
    {
      "rel": "http://webfinger.net/rel/profile-page",
      "type": "text/html",
      "href": "https://theattic.mjanssen.nl:443"
    },
    {
      "rel": "self",
      "type": "application/activity+json",
      "href": "https://theattic.mjanssen.nl:443/author/marco/"
    },
    {
      "rel": "http://nodeinfo.diaspora.software/ns/schema/2.0",
      "href": "https://theattic.mjanssen.nl:443/wp-json/nodeinfo/2.0"
    },
    {
      "rel": "http://nodeinfo.diaspora.software/ns/schema/1.1",
      "href": "https://theattic.mjanssen.nl:443/wp-json/nodeinfo/1.1"
    },
    {
      "rel": "http://nodeinfo.diaspora.software/ns/schema/1.0",
      "href": "https://theattic.mjanssen.nl:443/wp-json/nodeinfo/1.0"
    },
    {
      "rel": "https://feneas.org/ns/serviceinfo",
      "type": "application/ld+json",
      "href": "https://theattic.mjanssen.nl:443/wp-json/serviceinfo/1.0",
      "properties": {
        "https://feneas.org/ns/serviceinfo#software.name": "The Attic"
      }
    }
  ]
}`

**Comment by mediaformat** [comment]
When I tried fetching the profile `https://theattic.mjanssen.nl:443/author/marco/` (with ap accept headers) it was returning html and not json

**Comment by marc0janssen** [comment]
OK. What could the problem?If I search for the account via mastodon.social the don't get  avatar but I get a updated bioIf I search for the account via mstn.social I do get bio and avatar as aspectedIf I search via systems.discuss I get nothing. Seems mastodon server dependant. Verstuurd vanaf mijn iPhoneOp 13 dec. 2022 om 05:11 heeft Django ***@***.***> het volgende geschreven:﻿
When I tried fetching the profile https://theattic.mjanssen.nl:443/author/marco/ (with ap accept headers) it was returning html and not json

**Comment by marc0janssen** [comment]
Hi Django,

Found out the following

1.
Mastodon.social has a agressive caching (I guess). my activity pub data from Wordpress (avatar that is, bio is fine) is not updated. When I check it on mstdn.social/mastadon.nl/systems.discuss (and I think any other server) the data is just fine. everything is fetched and updated.

I don't know if you know micro.blog? They have activitypub also activated for their site. On mastodon.social their data is also not coming through. On mstdn.social/mastadon.nl/systems.discuss (and I think any other server) their data is coming through.

I guess this is a mastodon.social problem.

2.
My activitypub-plugin in wordpress something just seems to stop working (I noticed this in sitehealth in tools). I get a critical error. There is nothing to be done at that point to fix it (for me).

What I do is kill and clear my docker containers. Run docker compose  to all up and running again. Install my backup-plugin by hand. Restore the last backup from last night. And all is just fine.... I have no idea what causes this. I only know how to get this work around working. This not pretty and nice, but it works for the time being.

Maybe you can point out some stuff I can look at when the problem is occurring

**Comment by marc0janssen** [comment]
Error again:

Author URL is not accessible
ActivityPub
Your author URL https://theattic.mjanssen.nl:443/author/marco/ does not return valid JSON for application/activity+json. Please check if your hosting supports alternate Accept headers.


Gets annoying now.

**Comment by marc0janssen** [comment]
![CleanShot 2022-12-13 at 18 40 25@2x](https://user-images.githubusercontent.com/5788988/207405754-2c27fefc-0240-4bb8-832e-592267882ea7.png)

**Comment by marc0janssen** [comment]
When I only restore all the plugins from the backup, all the problems are gone again...

Is the activity pub plugin corrupting itself ???

**Comment by mediaformat** [comment]
It looks like you are using WP Fast Cache plugin. Caching plugins are known to interfere with the activitypub plugin!

**Comment by marc0janssen** [comment]
(Marco runs to kill that plugin)

**Comment by marc0janssen** [comment]
(how could you tell?)

**Comment by marc0janssen** [comment]
Colombo you are.... I will check the next few day if it stays stable.... (thanks for all the help)

**Comment by gbraad** [comment]
https://github.com/akirk/friends/issues/139

It seems favicon.ico is stored. Is this expected?

**Comment by pfefferle** [comment]
Is this still an issue?

**Comment by marc0janssen** [comment]
Yes, avatar never gets updated….

**Comment by pfefferle** [comment]
Is this still an issue?

**Comment by marc0janssen** [comment]
Yes. But close it. I don't mind anymore. Verstuurd vanaf mijn iPhoneOp 22 mei 2023 om 07:41 heeft Matthias Pfefferle ***@***.***> het volgende geschreven:﻿
Is this still an issue?

**Comment by pfefferle** [comment]
What platform do you use? Mastodon.social, seems to use the correct image:

![Bildschirmfoto 2023-05-22 um 15 33 37](https://github.com/Automattic/wordpress-activitypub/assets/2373/5d0f4816-85c1-4121-8fca-8b66b3c4dbd1)

**Comment by marc0janssen** [comment]
Hi Sorry,

For replying so late (I was in de US for a few days).
It’s seems fine, I did not care to check anymore. But now it works!
Thanks for your head up!

Marco

**Comment by YourAutisticLife** [comment]
I'm still having issues with my avatar refresh. 

I did set an avatar initially, and it transferred to my fediverse profile just fine.

However, I've since changed my avatar on WordPress (I wanted to distinguish it from my Mastodon account), but I'm still not seeing the change in my profile on the fediverse.

This is my WordPress handle: @yourautisticlife@www.yourautisticlife.com

I've checked it both from my own instance: mast.yourautisticlife.com
And from universeodon: https://universeodon.com/@yourautisticlife@www.yourautisticlife.com

Not sure if I should open a new issue...

**Comment by pfefferle** [comment]
Mastodon caches the avatar and there is no possibility to invalidate that cache. Have you posted a new blog-post since then? I may have heard that mastodon updates the cache when there is new activity.

**Comment by YourAutisticLife** [comment]
Yes, yes, yes. I've posted a ton of posts. I thought about the cache.

**Comment by camielschoonens** [comment]
If you are running your own Mastodon server you can force an account refresh with the following command.

`tootctl accounts refresh`

If you don’t have such access there is nothing more you can do but wait until the server refreshes the account at a certain interval.

**Comment by YourAutisticLife** [comment]
@camielschoonens Doing the `tootctl` command worked to refresh the information on my server. However, it is still not refreshed anywhere else. I checked with `universeodon.com` again. Still the old profile. I have a few ideas to test.

**Comment by YourAutisticLife** [comment]
Actually... I'm baffled now because what `mast.yourautisticlife.com` shows is very different than what `universeodon.com` shows.

This is a screenshot of my profile seen from `mast.yourautisticlife.com` (my Mastodon instance). There's no profile text. This is incorrect. The avatar is correct.

![Screenshot from 2023-08-23 11-43-26](https://github.com/Automattic/wordpress-activitypub/assets/136482210/72186281-f0b0-460c-8f71-6511ae95f7ba)

This screenshot is from `universeodon.com`. The profile text is correct. The avatar is wrong. There are also differences in the number of posts and the number of followers.

![Screenshot from 2023-08-23 11-43-40](https://github.com/Automattic/wordpress-activitypub/assets/136482210/0c58df9b-9a56-4911-84bf-754d190329b8)

The text of my profile was set ages ago. I changed the avatar a few weeks ago. This is all extremely confusing.

**Comment by mediaformat** [comment]
do you have any caching plugins on your own website?

**Comment by YourAutisticLife** [comment]
@mediaformat No caching plugins.

The problem is still present as of 1.0.0:

* I used `tootctl` to flush the cache on `mast.yourautisticlife.com`. The profile picture was changed. I notice now that the profile text is now synchronized, but I don't know what did it. (This is contrary to the screenshot above.)

* I look at the profile with `universeodon.com`, and it **still** shows the old picture.

**Comment by pfefferle** [comment]
I am no mastodon expert, but the cache might be configurable by the network admin?!?

**Comment by andrigamerita** [comment]
To anyone struggling here, I've found a solution, probably will make a pull request for it. My thought was that other instances didn't update their profile picture cache because when changing the profile picture on WordPress (which means, changing it on Gravatar), the URL of the picture stays the same. I don't know if this is standard or not, but in practice instances usually won't try to check if the content that a media URL points to has changed from time to time, but only refresh the media if the URL changes too. So, my solution is to simply make the ActivityPub plugin append something to the URL that doesn't break it, but makes it change. What I did is edit `wp-content/plugins/activitypub/includes/model/class-user.php`, and inside the `function get_icon()`, inside the `return` block, change the `'url'  => $icon,` to `'url'  => $icon . '#t=' . date('Ydm', time()),`, and in practice this makes it so the URL always has the current day string at the end, which means the URL is renewed everyday, and thus checked frequently enough by other instances. Use another time string instead of `Ydm` if you want to maybe update the URL every hour (so, `Ydmh`), but keep in mind that Mastodon still has aggressive caching, it could take 1 or 2 days for the pfp changes to be reflected, while other platforms (eg. Misskey) will usually try to update the image as soon as the URL changes.

**Comment by YourAutisticLife** [comment]
I should mention that I'm no longer experiencing this problem.

I've been wondering if WordPress needs some sort of profile edit to flush the information out, but I've never tested the idea.

(Before someone points out that it is *obvious* that a profile edit is needed, no it is not. Changing the Gravatar will change the profile picture shown **in** WordPress, but it won't automatically propagate to the fediverse.)

**Comment by iamwebrocker** [comment]
Hm, just thinking out loud here, but Is there a way to modify the timestamp idea to the date/time the avatar has changed? Or maybe add that cachbusting parameter with the first 8 digits of the md5 hash of the actual image?
If every AP enabled wordpress "fakes" a daily change to the profile image, and thus forces the instances to recapture and refresh their caches for no reason most times, isn't that a waste of resources (thinking of the scale if this is in every WP instance with the AP plugin active)

**Comment by pfefferle** [comment]
Version 2.0.0 has an update `Activity` on profile changes!

**Comment by YourAutisticLife** [comment]
I'm still having issues with this. I've updated my gravatar on https://www.thedailyisotope.com/ The WordPress blog itself shows the right gravatar. If I look at my profile on:

* mast.yourautisticlife.com, I get a default icon:

https://mast.yourautisticlife.com/tags/TheDailyIsotope

* dindon.one, I get the previous avatar I had set:

https://dindon.one/tags/TheDailyIsotope

(dindon.one is not special. It is just a site I have no control over.)

ETA: if I change the banner or the bio, the change appears to be pushed immediately.
