### ISSUE TITLE
Show likes from fediverse

### ISSUE THREAD

**Issue by jaschaurbach** [Automattic/wordpress-activitypub#235]
I have the webmention plugin installed and it shows the Likes to toots I made from my day-to-day account where I have a link to a blogpost inside. 

Likes made to the post of the blog are shown nowhere (which is a pitty). It would be great if the plugin could store likes received on the post the same way as the webmentions plugin which would display them as well as the likes.

**Comment by bekopharm** [comment]
Same for shares :+1:

**Comment by lapineige** [comment]
I would say it's every more interesting to know how many times (and by who) a content was shared :)

**Comment by bekopharm** [comment]
!keep

**Comment by gaviscapes** [comment]
Is there any progress on this? Very interested in this feature.

**Comment by pfefferle** [comment]
Keep

**Comment by janboddez** [comment]
On my own site, I just added like and "repost" ("Announce") support by means a couple custom `activitypub_inbox_{$type}"` callbacks.

Also added an `undo` callback, so that undoing the like/repost removes the "comment."

Since it's all implemented as action hooks, it would be very easy to add this to the ActivityPub plugin itself.

I do set some dummy content (in case I ever disable my site's "facepile" solution) and a couple comment meta fields allowing likes and reposts to be picked up by said "facepile" block. Maybe there's a better way (like "comment types," the way the Webmention plugin does it).

I think that's the main "challenge": deciding on a meta field "structure." It would be easy enough to update my block to extend compatibility to whichever solution ends up being implemented, so I don't really have a strong preference.

If there's any interest, I wouldn't mind opening a PR.

Also considering a (dynamic) Gutenberg block that would simply display a like and repost (filterable, preferably, so it can be made compatible with, e.g., webmentions) counter.

**Comment by pfefferle** [comment]
I would love to see a PR for that!!!

@janboddez btw. thanks for all your work/support so far!

**Comment by pfefferle** [comment]
Keep

**Comment by maltfield** [comment]
@janboddez have you also seen #929?

 * https://github.com/Automattic/wordpress-activitypub/issues/929

If you're already implementing a PR for this for "Like", would you also consider implementing "DisLike"?

**Comment by pfefferle** [comment]
@maltfield this is "only" for posts for now, it is not possible to up/down vote comments yet.

I would love to have a more generic approach that it will be possible to implement new activities with simple hooks and filters.
