### ISSUE TITLE
Redirect private and DM comments to author email

### ISSUE THREAD

**Issue by lapineige** [Automattic/wordpress-activitypub#326]
Currently private (follower-only visibility) and direct messages are discarded.
They can't be shown as comments for privacy reasons.

They could be redirected to post author email, so we are aware of them.

See: https://github.com/Automattic/wordpress-activitypub/issues/72#issuecomment-1543508330

**Comment by pfefferle** [comment]
I think this will come in a future version, but I like using `wp_mail` as a quick win.

**Comment by Cambridgeport90** [comment]
This should stay. I would like to see this on my own site at some point, in fact.

**Comment by lapineige** [comment]
Keep

**Comment by lapineige** [comment]
Keep

**Comment by solarbirdy** [comment]
Relatedly, I'm seeing that public but unlisted replies are not showing up either, similarly I suppose to locked replies. Is this intentional or an edge case that got thrown in with private? If it's intentional, the replies are public so I think should be treated the same as any other public reply. If it's an edge case, then I suppose it's a separate issue entirely.

[Here is a post I made today](https://solarbird.net/blog/2024/08/29/i-cant-believe-i-have-to-go-off-again-about-ex-twitter-already/) and [here is an unlisted but otherwise public comment that didn't show up](https://climatejustice.social/@SolarDavy/113046959839783019) on the blog.

**Comment by pfefferle** [comment]
@solarbirdy I would say it is on purpose, because I think mastodon uses a different identifier for unlisted posts (but I will re-check this).

I am also Not sure how others might see the "handle unlisted posts/replies as public" feature!?!

Maybe this has to be a setting?

**Comment by solarbirdy** [comment]
@pfefferle I don't know! I do know that in this specific case, OP told me that "public but unlisted" was used to keep replies from "spamming other peoples' timelines with my replies." They are fully aware it's public and are fine with that, and want people to be able to see it if they look, just not to put it in other peoples' "Home" timeline by default.

So that's at least one use case for this reply setting. I don't know about others.

**Comment by pfefferle** [comment]
This is now implemented in trunk and should be shipped with the next release!
