### ISSUE TITLE
Banner Image?

### ISSUE THREAD

**Issue by ambanmba** [Automattic/wordpress-activitypub#396]
The avatar image translates nicely to Mastodon, but is there a way to also do a banner image?

**Comment by moodler** [comment]
How did you get an avatar image for the main site blog?

**Comment by iamwebrocker** [comment]
the avatar image and banner image for a main site blog are retrived from the theme options. learned the hard way because I use a self-made theme and never bothered to add theme options. :-) If you have a theme with those options, look for `Design -> Customizer -> Header Image` for the banner image. The avatar is the "website icon" in the custimizer.

**Comment by moodler** [comment]
Many thanks for the detailed info.  I'm using GeneratePress, and I thought I'd set all those, but I'll fiddle with something hardcoded like this.  (I see something converted things to SVG along the way too which might have been it)

**Comment by iamwebrocker** [comment]
Hi,

what makes this tricky to debug: depending on the instance there may be a stubborn cache involved, and even if your site is now using the site icin and custom header options, they won't show for quite a while in the fediverse.

I don't know if/how you would alter the function.php of a highly customisable theme like site press, but in theory it should use the options mentioned under the hood already.
You can see here https://github.com/Automattic/wordpress-activitypub/blob/7855437c5c287eb87ecdd685aeff6affc6032f2a/includes/model/class-blog-user.php#L149

which options are used for the avatar (and a few lines further down the one for the banner image)
