### ISSUE TITLE
Feature Request: about the new Followers page

### ISSUE THREAD

**Issue by cybeardjm** [Automattic/wordpress-activitypub#456]
### What

It would be nice to be able to search and sort followers.
Defining the number of lines per page would be cool too...
It would be useful to group followers by instance.

### Why

Been using the plugin for a long time and now have 60+ followers on 1 of my 2 blogs, which means an unordered list of people on 3 pages (and with the migration, most of them now appear on almost the same date). When I try to locate a follower (usually one of mines, for testing purposes...), I have to browse the list in full...

**Comment by edent** [comment]
Right, I think I *almost* know how to do this :-)

In: 

https://github.com/Automattic/wordpress-activitypub/blob/fd6cb84ba3df13049f181e47d74548fcffb16a8e/includes/table/class-followers.php#L44

We can add the columns which we want to be sortable. For example:

```php
$sortable_columns = array(
   'name' => array( 'name', true ),
   'updated' => array( 'updated', false )
);

return $sortable_columns;
```

Clicking on one of those columns loads the page at `wp-admin/options-general.php?page=activitypub&tab=followers&orderby=name&order=asc`

So we can take the `orderby` and the `order` and pass them to:

https://github.com/Automattic/wordpress-activitypub/blob/fd6cb84ba3df13049f181e47d74548fcffb16a8e/includes/collection/class-followers.php#L326

For example:

```php

		$orderby = isset( $_GET['orderby'] ) ? $_GET['orderby'] : "name";
		$order   = isset( $_GET['order']   ) ? $_GET['order']   : "order";
		echo $orderby;
		echo $order;
		$defaults = array(
			'post_type'     => self::POST_TYPE,
			'posts_per_page' => $number,
			'paged'     => $page,
			'orderby'   => $orderby,
			'order'     => $order,
			...
```

**But** the ordering is completely wrong, because those fields are in the meta_value. See:

https://github.com/Automattic/wordpress-activitypub/blob/fd6cb84ba3df13049f181e47d74548fcffb16a8e/includes/collection/class-followers.php#L230

and

https://github.com/Automattic/wordpress-activitypub/blob/fd6cb84ba3df13049f181e47d74548fcffb16a8e/includes/model/class-follower.php#L311

And that's where I get stuck...
