### ISSUE TITLE
Feature Request: Replace images with their alt text?

### ISSUE THREAD

**Issue by edent** [Automattic/wordpress-activitypub#466]
### What

I have a blog post with lots of images in it.  Most ActivityPub clients don't support inline images. So this plugin removes those images.

I'd like to have it replace the image with its alt text.

### Why

A typical blog post might say:

```html
<p>To see your followers, click the relevant link.<p>
<img src="image.png" alt="Screenshot of the settings page. The 'followers' link is highlighted in red.">
<p>Enjoy!</p>
```

### How

Within the body of the ActivityPub message, I think the plugin should insert:

```
[Image: "Screenshot of the settings page. The 'followers' link is highlighted in red."]
```

Or similar.

There's a short discussion at https://mastodon.social/@Edent/111099581981059278

NB, this is a different request to #94. I'm not talking about the alt of the attached image - I mean to put the alt text inline with the post.

**Comment by janboddez** [comment]
As per that little discussion :-D, I think in the case of the specific example above, you _could_ get away with just having the image stripped. I.e., the status would _still_ be readable if the image was attached below it, with the correct alt text.

Otherwise, I'd have a look at the `activitypub_the_content` filter. I've had some success with https://gist.github.com/janboddez/58a2f3d2c86717cd799048af651fa6b4#file-activitypub-php-L77-L92. (In that example, if you added `img` to the "allowed tags" and then used, e.g., a regular expression to replace images with something more meaningful, that _should_ work. I'm aware such an approach requires quite a bit of PHP knowledge and that regexes aren't generally very robust [even if WordPress is full of them]. But it _could_ work, at least temporarily.)

**Comment by edent** [comment]
So, I think this works:

In:

https://github.com/Automattic/wordpress-activitypub/blob/963b2795a617ca6e94ecd7eb84249b997423c59b/includes/transformer/class-post.php#L38

Add:

```php
	protected $allowed_tags = array(
		'img' => array(
			'alt' => array(),
		),
```
Means that every image is replaced with `<img alt="Whatever" />`

Which means this relatively simple regex can replace the image with the alt:

```php
$pattern = '/<img\s+alt="([^"]*)"\s\/>/';

preg_match_all($pattern, $content, $matches);

foreach ($matches[0] as $imgTag) {
    preg_match($pattern, $imgTag, $altMatch);
    $altText = $altMatch[1];
    $wrappedText = "[Image:  " . $altText . "]\n";
    $content = str_replace($imgTag, $wrappedText, $content);
}
```

Obviously parsing HTML with a regex is naughty - but the HTML outputted by `wp_kses` is consistent. It probably needs some hardening, and also probably needs an option adding in the settings. If a stray `<img>` does slip through, it will be silently dropped by the receiver (if it doesn't understand it) or simply not display (as there's no `src`).

But it has worked on my posts - see https://mastodon.social/deck/@blog@shkspr.mobi/111102929394329255

**Comment by pfefferle** [comment]
I thought a lot about removing the `wp_kses` completely, to let other platforms choose what they want to allow and what not. This way, we would better support friendi.ca and Mastodon would simply do what `wp_kses` do now.

What do you think?

/cc @mattwiebe @jeherve @mediaformat @akirk

**Comment by aslakr** [comment]
The result would be that anything goes? Even #452?

**Comment by pfefferle** [comment]
it would then all be supported by WordPress, but could still be ignored by other platforms like mastodon.

**Comment by pfefferle** [comment]
@edent with 1.0.2 you will now be able to add your changes using a filter and without doing any other tweaking.

**Comment by edent** [comment]
@pfefferle is there a list of filters which are available? Thanks.
