### ISSUE TITLE
Wordpress reports ActivityPub System Scheduler not configured

### ISSUE THREAD

**Issue by chrisale** [Automattic/wordpress-activitypub#525]
### Quick summary

Hi all,

My wordpress site is reporting in the Site Health Status the following even though the cron job is configured as stated in the message:
System Task Scheduler not configured
ActivityPub
Enhance your WordPress site’s performance and mitigate potential heavy loads caused by plugins like ActivityPub by setting up a system cron job to run WP Cron. This ensures scheduled tasks are executed consistently and reduces the reliance on website traffic for trigger events.
![Screenshot 2023-10-18 at 08 59 16](https://github.com/Automattic/wordpress-activitypub/assets/1987081/9e4861da-7e77-471f-b096-be5ea0a87f58)

### Steps to reproduce

troubleshooting

### What you expected to happen

Cron job is active with 
14 * * * * wget --delete-after https://www.alberniweather.ca/wp-cron.php

### What actually happened

Site Health reports Activity Pub Site Scheduler not running.

### Impact

All

### Available workarounds?

There is no user impact

### Logs or notes

Shared Hosting Platform/CPanel (whc.ca)
ActivityPub, NodeInfo and Friends plugins installed.

**Comment by janboddez** [comment]
Found this issue because I too was experiencing heavy load when publishing new posts.

Looks like @chrisale has their cron job set up okay; however, the plugin (or WordPress itself) can't know this. It merely checks if the `DISABLE_WP_CRON` constant was defined.

The check is still right, though. The ActivityPub plugin schedules POST requests to run almost immediately, and they will run on the very next request, which very well may be while the post can still be considered saving (i.e., the block editor, if I'm not mistaken, is known to kick off several requests, at least under certain circumstances).

The only way to prevent that, is to set `DISABLE_WP_CRON` to `true`. (And invoke wp-cron using a separate system cron job, because else scheduled tasks would never get run.)

**Comment by pfefferle** [comment]
Thanks a lot @janboddez I will remove the warning for now, because it seems to be better to have both a systems cron and the page load cron.

I will see what I can do instead to remind people to also configure a systems cron.

But with also handling delete and update Activities for Actors, the systems crons will not be as important as they were before.
