### ISSUE TITLE
Feature Request: Add application to post and reply context

### ISSUE THREAD

**Issue by jeherve** [Automattic/wordpress-activitypub#868]
### What

The Mastodon API seems to support an `application` field, that allows one to pass information about the client used to post the message. Here are some examples:

```json
"application":{"name":"Web","website":null}
```
-- https://mastodon.social/api/v1/statuses/112989821694410467

```json
"application":{"name":"Ivory for iOS","website":"https://tapbots.com/"}
```
-- https://mastodon.social/api/v1/statuses/112993223143821397

This information is used by some Fediverse applications to display information about how the message was posted:

<img width="364" alt="image" src="https://github.com/user-attachments/assets/18f5a254-7397-4d1b-b35d-ea235204d5aa">

API Reference: https://docs.joinmastodon.org/entities/Application/

It would be nice if messages posted via the ActivityPub plugin included that information, maybe as a "ActivityPub for WordPress" application?

### Why

This would help further promote the ActivityPub plugin and nurture its adoption.

**Comment by mediaformat** [comment]
Might be good to make it pluggable too, so that @akirk EMA plugin could hook into

**Comment by pfefferle** [comment]
I think it is the other way around! I would use a filter of EMA to implement it?!?

**Comment by akirk** [comment]
I had researched this in https://github.com/akirk/enable-mastodon-apps/issues/153 and it turns out that the application info is not federated between Mastodon, it is only tracked inside your own Mastodon instance by using an `application_id` field which refers to an app (see `website` [in the view](https://github.com/mastodon/mastodon/blob/97f6baf977212e84125ac325176ad305ad5b068a/app/views/statuses/_detailed_status.html.haml#L53-L57) and [in the db model](https://github.com/mastodon/mastodon/blob/97f6baf977212e84125ac325176ad305ad5b068a/db/schema.rb#L765-L781)) authenticated at the Mastodon instance, you cannot feed your own data into that.

**Comment by pfefferle** [comment]
Closing this for now, until Mastodon supports a way to federate this.

Thanks for the infos @akirk
