### ISSUE TITLE
Fediverse Creator - limited options and incorrect syntax

### ISSUE THREAD

**Issue by edent** [Automattic/wordpress-activitypub#884]
### Quick summary

The new plugin adds:

`<meta property="fediverse:creator" name="fediverse:creator" content="blog@shkspr.mobi" />`

[As per the specification](https://blog.joinmastodon.org/2024/07/highlighting-journalism-on-mastodon/), the "property" isn't needed. The example given is:

`<meta name="fediverse:creator" content="@Gargron@mastodon.social" />`

Not all users will have their blog's name as their primary AP name. For example, I use my Mastodon handle. Perhaps this should be user selectable?

Incidentally, [the meta element doesn't need a closing `/`](https://html.spec.whatwg.org/multipage/semantics.html#the-meta-element)

### Steps to reproduce

1. Enable the plugin
2. View source.

### What you expected to happen

* Let the user set the creator name.
* Use the correct syntax

### What actually happened

Syntax is slightly incorrect causing minor psychic distress to nerds like me!

### Impact

All

### Available workarounds?

No but the platform is still usable

**Comment by pfefferle** [comment]
> Incidentally, [the meta element doesn't need a closing /](https://html.spec.whatwg.org/multipage/semantics.html#the-meta-element)

Yes, it does not have to be self-closing, but if you want to be XHTML compatible, you should add it. Besides of that, it is the default way WordPress handles metas and links.

> [As per the specification](https://blog.joinmastodon.org/2024/07/highlighting-journalism-on-mastodon/), the "property" isn't needed. The example given is:

The problem here is, that it is not an [OGP extension](https://ogp.me/) if it has no `property`, so I decided to add both. It should not break anything and might be ready for possible changes that might come in next versions to be fully OGP compatible. Mastodon also supports the `property` attribute btw.

**Comment by mikka2061** [comment]
In addition, the meta should open with a trailing @ sign, if I am not mistaken. Currently, mine shows

`<meta property="fediverse:creator" name="fediverse:creator" content="mikka@mikka.is" />`

when the proper syntax should be 

`<meta property="fediverse:creator" name="fediverse:creator" content="@mikka@mikka.is" />`

**Comment by mikka2061** [comment]
@pfefferle 

> https://blog.joinmastodon.org/2024/07/highlighting-journalism-on-mastodon/

That's however sadly a function of the Outlookification of the Fediverse by Mastodon. The *fish/*key Implementation (no idea how others will handle it, I presume it'll be "Mastodon forced our hand") which predates Mastodon uses `const usernameServerRegex = /@[\w.-]+@` for this. I'll put in a PR for some of the fish-clones to acquiesce to Gargron, but since it's neither hair nor hide, maybe add the @ in the Plugin?

**Comment by pfefferle** [comment]
But the `@` is something that came up with Twitter and was adopted by Mastodon, the pure WebFinger ID is without the `@`, so it is always harder to handle the `@webfinger` over the pure `webfinger` habdle. That's why I technically prefer the `@`-less version and because this is not user facing, I am not sure if it will ever break something!?!

**Comment by mikka2061** [comment]
Ah, you're absolutely right. I stand corrected. (I'd argue, that @ predates Twitter from those IRC days of yore, I wonder if Wusel knows more about that, but you're nevertheless correct). Sending PRs out.

**Comment by pfefferle** [comment]
I will close this for now, please re-open if you think it is still something to do.
